spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
